import type { ID, Priority, Timestamp } from './common.types';

export interface Task {
  id: ID;
  title: string;
  description: string;
  priority: Priority;
  dueDate: string;
  completed: boolean;
  tags: string[];
  createdAt: Timestamp;
}

/** Partial input for creating a task — id and createdAt are generated by the store */
export type CreateTaskInput = Omit<Task, 'id' | 'createdAt'>;

/** Partial update — all fields optional except id */
export type UpdateTaskInput = Partial<Omit<Task, 'id'>>;
